### ISSUE TITLE
Error when importing Vec

### ISSUE THREAD

**Issue by MaiaVictor** [UlfNorell/agda-prelude#53]
When importing `Vec`, I get the following error:

```
/Users/v/vic/dev/agda/agda-prelude/src/Prelude/Vec.agda:125,3-86
Repeated variables in pattern: y
when scope checking the left-hand side
less-trans {{OrdLawsVec {A = A}}} {x ∷ xs} {y ∷ ys} {y ∷ zs}
(head< lt) (tail< lt₁)
in the definition of OrdLawsVec
```

Using `Agda version 2.5.3-e3f5983-dirty`.

**Comment by UlfNorell** [comment]
Is this on the `compat-2.5.3` branch? The `master` branch is not compatible with Agda `2.5.3`.

**Comment by MaiaVictor** [comment]
Okay, thanks.

**Comment by MaiaVictor** [comment]
Is `Prelude.Nat.Properties` not on the compat branch? What Agda version exactly the master branch uses?

**Comment by UlfNorell** [comment]
The master branch is kept in sync with the [Agda stable-2.5 branch](https://github.com/agda/agda/tree/stable-2.5). I'm afraid I'm not very good at back-porting new things to the compat branches. Part of the reason is that it takes work, but another reason is that it lets me reorganise things without worrying too much about breaking people's code.

**Comment by MaiaVictor** [comment]
You shouldn't need to do that! I'll update Agda to stay in sync with master. Thanks!
